language: java
jdk:
- oraclejdk8
env:
  global:
  - secure: SWU1tSzUvXW79LKcCpF9szImWw8GVGKNPgynq0+dk4jsnd7QSDYXiU1O79yKLEaJPRtVnpL+XJnrro2C0w0Mr+OdKnC5wzfbOuqMenGp+7zvmcoeYLwbEh/mXH9Sr5dfiV22hF8CLmWN1Xg3grprgR/XgSNVNnurEiVVuceCP3p1G7xRwPxNxbb0LzHsde9wFLfFZ4V9RltifkQ9s3TGpiwmztwCqwx0QlRaWpagh6gApEVR6imVaTQJshTJcV61Zfuy92AYzfO8YPwLI/ftjVKbfMyU9EZz5/qMz0f2W+YGN/9ngkQzTy4n2zx5y69y+TkihajANTmKqRRENos8SoB5sE6AoHaKo6xXg4lzo8r6NX56ZyPMQbCPRYyQShx4KSrbgRkLaH3Rfa4SgHNstcOy2OFISLvGzyf6Shv2/GriDQDKImsXcHiTdEM+6ZNwBriQu+5Gg1gZPzJEM1Hvezc+C4cu2hsRdDW3xJmO870v7jg7ovHee7vTCmbVjihc7XEDDIPIc/nA9qhwsMkRPs8Pp2RBUHDXaaSjJPtqA+DFO+Ip25X0If1OOzYzNWv7huYpp+8FP9YUnR+3ajnZup8No4Csx00z2fuMzYdt8CNpiLNsaNfjTbM02s+C8zUiTcniSg8U9BE4ay/jza2HxwLLur1wd6Mo0Gn3Ld+dvCo=
  - secure: sjYjZXQmK+KRTeEtN9ObOjsqBA+TjeJVxh28fThkwYyYSa1Y69+q9C4ItY4lc2r4bGqTO2LVo//IbATHwtuD2gQvWOOZULImo8RnOvNlGSgFeOyn/6d8CEoIkrf5u1wbfsyCyBqNfUIybtOKyMKllGDy25f08OBZziuIQYdjsUoBeMFr2tkr70A0n/tLi51m/n/DtiTsS0t2M+m76jhPvoXysE9NHmYd16JxLG8Wf33J24+bXu5NsSNHho/VjpaATjza1KY+43IRBxasVOpdHhXOw8/HB7Yf2fPlTwErPMZ+YFrhGqbUBfypVUj2X2jbO/yHM0ZSlj0ZEPfYdvgjXgwveYhbnR/MBlA3MUgMCE5LmSN/2YB/r3KnVtk/DhKBdoSdGi8/CbPvw78/eEDSn6uWQ/bYaKBf+yWga9Us3m/udUKyF4Lb0Aty9t/K6GW4V2+pD/gZ441xZG7omksCqWXbVWT0nv5DsPW8zAzrk3HLdA2I9AhMllWibPHj6Ml3hd6meAbmVEJZ/DsvGo2zhECCpHgY89s0Tuf8WKp9KSHm6F9hCLS57Dr1THLD0Ifa8PpEZNcDIphnaSVaRQchPsRCms4oEkiR7kOrfaYyD6/9bjhU11EBWteKUARPyUsvjyCKozDIs5p9U+mEgMRt7YL2dnnl7PpDXAUP6it81Ts=
before_install:
- cp .travis.maven.settings.xml $HOME/.m2/settings.xml
script:
- set -e
- bash .travis.deploy.artifacts.sh
notifications:
  email:
    recipients:
    - julien@julienviet.com
    on_success: always
    on_failure: always
